A common calculation is one that spans over time and models the growth or decline of something.  

If there is a growth rate included, this can be solved using a loop.

At the end of each period, we calculate the interest and add it to the previous balance.
We also add the payment for that period.

Note that are payments are at the end of the period and don't get figured into the interest.

We can create a separate variable for each year and then do the calculation.

In [1]:
payment = 1000.
interest_rate = 0.05

b0 = payment
b1 = b0 * interest_rate + b0 + payment
b2 = b1 * interest_rate + b1 + payment
b3 = b2 * interest_rate + b2 + payment
b4 = b3 * interest_rate + b3 + payment
b5 = b4 * interest_rate + b4 + payment
b6 = b5 * interest_rate + b5 + payment
b6

8142.008453125

We can use an array here instead of separate variables for each year.

In [2]:
payment = 1000.
interest_rate = 0.05

import numpy as np
b = np.array([0,0,0,0,0,0,0])
b[0] = payment
b[1] = b[0] * interest_rate + b[0] + payment
b[2] = b[1] * interest_rate + b[1] + payment
b[3] = b[2] * interest_rate + b[2] + payment
b[4] = b[3] * interest_rate + b[3] + payment
b[5] = b[4] * interest_rate + b[4] + payment
b[6] = b[5] * interest_rate + b[5] + payment
b

array([1000, 2050, 3152, 4309, 5524, 6800, 8140])

If we look closely, we can notice a pattern.
By using the loop programming technique, we can simplify this calculation and make it easier to understand.

In [3]:
import numpy as np
payment = 1000.
payments = np.ones(10) * payment
payments

array([ 1000.,  1000.,  1000.,  1000.,  1000.,  1000.,  1000.,  1000.,
        1000.,  1000.])

In [4]:
balance = np.zeros(10)
balance

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

We now want to fill up the balance with the values from our growing investment.

In [5]:
interest_rate = 0.05
balance[0] = payment
for i in range(1, len(payments)):
    balance[i] = balance[i-1] + balance[i-1] * interest_rate + payment

In [6]:
balance

array([  1000.        ,   2050.        ,   3152.5       ,   4310.125     ,
         5525.63125   ,   6801.9128125 ,   8142.00845313,   9549.10887578,
        11026.56431957,  12577.89253555])

In [7]:
# Here we perform a five percent annual interest compounded monthly
import numpy as np
payment = 1000.
balance = np.zeros(84)
interest_rate = 0.05 / 12
balance[0] = payment
for i in range(1, len(balance)):
    balance[i] = balance[i-1] + balance[i-1] * interest_rate + payment
print(balance)

[   1000.            2004.16666667    3012.51736111    4025.06951678
    5041.84063977    6062.8483091     7088.11017706    8117.64396946
    9151.467486     10189.59860052   11232.05526136   12278.85549162
   13330.0173895    14385.55912862   15445.49895832   16509.85520398
   17578.64626733   18651.89062678   19729.60683772   20811.81353288
   21898.5294226    22989.7732952    24085.56401726   25185.920534
   26290.86186956   27400.40712735   28514.57549038   29633.38622159
   30756.85866418   31885.01224194   33017.86645962   34155.4409032
   35297.7552403    36444.82922047   37596.68267555   38753.33552003
   39914.80775137   41081.11945033   42252.29078137   43428.34199296
   44609.29341793   45795.16547384   46985.97866332   48181.75357441
   49382.51088097   50588.27134298   51799.05580691   53014.8852061
   54235.78056113   55461.76298013   56692.85365921   57929.07388279
   59170.44502397   60416.98854491   61668.72599718   62925.67902217
   64187.86935142   65455.31880706   6

In [8]:
## annuity formula to check result
i = 0.05 / 12
n = 84
((1+i)**n - 1)/i

100.32865253424956